CREATE TABLE if not EXISTS `file` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(32) NOT NULL,
  `url` longtext,
  `name` varchar(256) NOT NULL,
  `md5` varchar(64) NOT NULL,
  `size` bigint(20) DEFAULT NULL,
  `download_count` int(11) DEFAULT NULL,
  `file_type` smallint(6) DEFAULT NULL,
  `location` smallint(6) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `ip` varchar(64) DEFAULT NULL,
  `auth_id` bigint(20) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `created_by` bigint(20) DEFAULT NULL,
  `updated` datetime(6) DEFAULT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `file_md5_221b6428` (`md5`),
  KEY `file_file_type_1d3197f0` (`file_type`),
  KEY `file_location_ada5bdd9` (`location`),
  KEY `file_is_deleted_d10a4732` (`is_deleted`),
  KEY `file_auth_id_734d2086` (`auth_id`)
) ENGINE=InnoDB AUTO_INCREMENT=277 DEFAULT CHARSET=utf8;