CREATE TABLE if not EXISTS `voucher` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(24) NOT NULL,
  `status` smallint(6) DEFAULT NULL,
  `ops` smallint(6) DEFAULT NULL,
  `task_id` varchar(64) DEFAULT NULL,
  `process_count` int(11) DEFAULT NULL,
  `query_count` int(11) DEFAULT NULL,
  `is_failed` tinyint(1) DEFAULT NULL,
  `fail_reason` varchar(512) DEFAULT NULL,
  `extra_info` longtext,
  `time_waiting` datetime(6) DEFAULT NULL,
  `time_preparing` datetime(6) DEFAULT NULL,
  `time_processing` datetime(6) DEFAULT NULL,
  `time_finished` datetime(6) DEFAULT NULL,
  `url_callback` varchar(256) DEFAULT NULL,
  `is_callback` tinyint(1) DEFAULT NULL,
  `callback_ret` varchar(512) DEFAULT NULL,
  `time_callback` datetime(6) DEFAULT NULL,
  `callback_count` int(11) DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `ip` varchar(64) DEFAULT NULL,
  `auth_id` bigint(20) DEFAULT NULL,
  `created` datetime(6) DEFAULT NULL,
  `created_by` bigint(20) DEFAULT NULL,
  `updated` datetime(6) DEFAULT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `voucher_status_53be5361` (`status`),
  KEY `voucher_ops_a79b385f` (`ops`),
  KEY `voucher_is_failed_44d73df2` (`is_failed`),
  KEY `voucher_is_callback_6c031483` (`is_callback`),
  KEY `voucher_is_deleted_944cdd23` (`is_deleted`),
  KEY `voucher_auth_id_0503ab29` (`auth_id`)
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8;
